# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [4]:
A = np.arange(1, 16).reshape(3,5)

In [9]:
#Generate array from 1 to 15
B=np.arange(1,16)
print(B)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [13]:
#From Array B put it in a matrix with 3 blocks of 5 values (3x5=15 values)
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [24]:
K = np.ones((3,3))
print(K)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
# Generate an array with number from 1 t0 9, and put this array in a matrix with a 3x raws and 3 columns
B = np.arange(1, 10).reshape(3, 3)
# generate a matrix with 3 blocks of 3 values (3x3=9 values)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [27]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [30]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [32]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [40]:
#This is the second raw of the Matrix A
# where first raw is A[0], and thirs raw is A[2]

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [42]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [44]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [56]:
a = np.arange(30)
b= a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [62]:
# a is a array from 1 to 29
# b=a.reshape((2,3)) will not work as we cannot have 2 blocks of 3 values (2x3=6 values and we have 30 values)
# b=a.reshape((2,3,5)) will work as 2x3x5 = 30 values
# b=a.reshape((2,3,-1)) 


In [64]:
m = a.reshape((2,3,5))
print(m)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [67]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [69]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [71]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [88]:
def add_mult_matrices(v1, v2, func):
    if func == "add":
        result = v1 + v2
    elif func == "multiply":
        result = v1*v2
    else:
        raise ValuError("use add or multiply")
    return result

k = np.array([1,2])
l = np.array([3,4])
c = add_mult_matrices(v1=k, v2=l, func="add")
d = add_mult_matrices(v1=k, v2=l, func="multiply")
print('result of add matrix k and matrix l is:',c)
print('result of multiply matrix k and matrix l is:',d)

result of add matrix k and matrix l is: [4 6]
result of multiply matrix k and matrix l is: [3 8]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [175]:
x = np.array([4,3])
x

array([4, 3])

In [177]:
#Vilken dimension har vektorn x?
y = len(x)
y

2

In [179]:
#Beräkna 5x
z = 5*x
print(z)

[20 15]


In [181]:
#Beräkna 3x
t = 3*x
print(t)

[12  9]


In [183]:
#Beräkna 5x + 3x
f = z + t
print(f)

[32 24]


In [185]:
#Beräkna 8x
d = 8*x
print(d)

[32 24]


In [187]:
#Beräkna 4x - x
i = 4*x - x
print(i)

[12  9]


In [189]:
#transpose x
zi = x.transpose()
print(zi)

[4 3]


In [191]:
x = np.array([4,3])
zit = len(x.transpose())
zit

2

In [193]:
#Är x + x.transpose() definierat?
abc = x + x.transpose()
print(abc)

[8 6]


In [195]:
#Beräkna np.sqrt(x.transpose()*x)
x = np.array([4,3])
abcd = np.sqrt(np.dot(x,x.T))
print(abcd)

5.0


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [253]:
#10.2.1

In [255]:
A = np.array([[2,1,-1],[1,-1,1]])
print(A)

[[ 2  1 -1]
 [ 1 -1  1]]


In [257]:
B = np.array([[4,-2,1],[2,-4,-2]])
print(B)

[[ 4 -2  1]
 [ 2 -4 -2]]


In [259]:
C = np.array([[1,2],[2,1]])
print(C)

[[1 2]
 [2 1]]


In [261]:
D = np.array([[3,4],[4,3]])
print(D)

[[3 4]
 [4 3]]


In [263]:
E = np.array([1,2])
print(E)

[1 2]


In [265]:
I = np.array([[1,0],[0,1]])
print(I)

[[1 0]
 [0 1]]


In [267]:
#(a) 2A
2*A

array([[ 4,  2, -2],
       [ 2, -2,  2]])

In [269]:
#(b) B-2A
B-2*A

array([[ 0, -4,  3],
       [ 0, -2, -4]])

In [271]:
#(c) 3C - 2E
3*C -2*E

array([[ 1,  2],
       [ 4, -1]])

In [273]:
#(d) 2D - 3C
2*D - 3*C

array([[3, 2],
       [2, 3]])

In [275]:
#(e) D.T + 2D
D.T + 2*D

array([[ 9, 12],
       [12,  9]])

In [277]:
#(f) 2C.T - 2D.T
2*C.T - 2*D.T

array([[-4, -4],
       [-4, -4]])

In [333]:
#(g) A.T -B not possible
# A.T -B.T possible
A.T - B.T

array([[-2, -1],
       [ 3,  3],
       [-2,  3]])

In [329]:
#(h) AC not possible
# A.T*C possible
np.dot(A.T,C)

array([[ 4,  5],
       [-1,  1],
       [ 1, -1]])

In [307]:
#(i) CD
C*D

array([[3, 8],
       [8, 3]])

In [321]:
#(j) CB 
# CB not possible 
# C.T*B possible
np.dot(C.T,B)


array([[  8, -10,  -3],
       [ 10,  -8,   0]])

In [311]:
#(k) CI
C*I

array([[1, 0],
       [0, 1]])

In [317]:
#(l) AB.T
np.dot(A,B.T)

array([[5, 2],
       [7, 4]])

In [ ]:
#10.2.2 Beräkna A*A.T

In [199]:
A = np.array([[2,3,4],[5,4,1]])
print(A)

[[2 3 4]
 [5 4 1]]


In [201]:
B = A.T
print(B)

[[2 5]
 [3 4]
 [4 1]]


In [207]:
C = np.dot(A, A.T)
print(C)

[[29 26]
 [26 42]]


In [209]:
#10.2.3

In [215]:
A = np.array([[1,2],[2,4]])
print(A)

[[1 2]
 [2 4]]


In [217]:
B = np.array([[2,1],[1,3]])
print(B)

[[2 1]
 [1 3]]


In [219]:
C = np.array([[4,3],[0,2]])
print(C)

[[4 3]
 [0 2]]


In [223]:
#Compute AB
AB = np.dot(A,B)
AB

array([[ 4,  7],
       [ 8, 14]])

In [225]:
#Compute AC
AC = np.dot(A,C)
AC

array([[ 4,  7],
       [ 8, 14]])

In [ ]:
# One can see that AB = AC, while matrix B different to matrix C

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [90]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [92]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [94]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
